### PR TITLE
Update ports package in Asgard to 6.0.0 (from 5.0.1)

### PR DESCRIPTION
**Pull request by RichardCrawshaw**
Brings into line with Asgard.Console.

### CODE REVIEW

**Comment by JamesThorpe** [comment]
If we’re consolidating to 6 - may be worth updating the GitHub build action to use 6 too. I had to retarget the console app to 5 since that’s what the template was on. Don’t think there’s any reason the whole thing can’t just be on 6 though.

**Comment by RichardCrawshaw** [comment]
I was doing stuff with NuGet packages: specifically updating Gledsheimr to 0.9.1-beta? when I saw that this needed to be consolidated. So I updated to 6 as that's what the Console app was using. So lets move everything to 6. If that breaks then we can always regress back to 5.1.
However, I need to either publish Gledsheimr 0.9.1-beta4, or up the version to 0.9.1 and publish that before Asgard will pass the check-in validation. So let me sort that out first.

**Comment by RichardCrawshaw** [comment]
Updated Gledsheimr to 0.9.1; NuGet is doing it's thing. It might take an hour...

**Comment by RichardCrawshaw** [comment]
NuGet's thing is done!

**Pull request merged**
