### PR TITLE
multiple registrations, filtering

### PR DESCRIPTION
**Pull request by JamesThorpe**

### CODE REVIEW

**Comment by RichardCrawshaw** [comment]
Probably worth changing the Func<T, bool> to Predicate<T>; simplifies the types. There are a number of null dereference warning.

**Comment by JamesThorpe** [comment]
Thanks - wasn't aware of the `Predicate<T>` type.  Makes sense to switch the `MessageManager` filtering to use it too.  Turning on `nullable` is still fairly new to me - need to get to grips with those warnings!

**Comment by JamesThorpe** [comment]
Looks like only one of the warnings was in the updated code - the rest exist elsewhere already. Will need to go through them carefully and choose the right behaviour for each - suspect some can be early returns, others should probably throw

**Comment by RichardCrawshaw** [comment]
I had gone through all the reported warnings and eliminated them prior to my last push or two. The GitHub build may have identified some that weren't reported on locally, or you might have older versions (not sure how though). Those are the only things I can think off.

**Comment by RichardCrawshaw** [comment]
I really want to pull your branch down and look at the code in VS, but I can't see how to get the remotes visible in VS. Still googling...

**Pull request merged**
